"""Fix model relationships

Revision ID: 522f02b602ae
Revises: 4acc3a3f1e3f
Create Date: 2025-11-01 12:34:04.761231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522f02b602ae'
down_revision = '4acc3a3f1e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notes_project_id'))
        batch_op.drop_column('project_id')

    op.drop_table('note_revisions')
    # ### end Alembic commands ###
