"""Make project_id NOT NULL for notes

Revision ID: 7399908c7831
Revises: 8f70442a069c
Create Date: 2025-11-01 13:40:06.439993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7399908c7831'
down_revision = '8f70442a069c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
